### ISSUE TITLE
Kronos Site

### ISSUE THREAD

**Issue by ghost** [mgerb/ps-launcher#4]
Kronos site directs to twinstar.cz when it should direct to Kronos-WoW.com

**Comment by mgerb** [comment]
Good catch, I'll fix this. I'm currently working on functionality to adjust server info.

**Comment by mgerb** [comment]
Interesting enough 'https://www.kronos-wow.com' redirects to the twinstar site whereas the HTTP version links to the correct site.

**Comment by mgerb** [comment]
This will be updated in the latest release. Closing.
